### ISSUE TITLE
Error deploying from bastion (ubuntu) server

### ISSUE THREAD

**Issue by aw30** [Connexions/cnx-deploy#7]
I know it's good practice to build on the local box and ship, but is there a reason that this cannot be done on the destination box? This is for initial deployment generally, so it shouldn't cause any adverse affects after said deployment.
____________________________________________________
< TASK [install nodejs and npm packages (on Debian)] >
----------------------------------------------------
       \   ^__^
        \  (oo)\_______
           (__)\       )\/\
               ||----w |
               ||     ||

failed: [127.0.0.1] => (item=bin) => {"failed": true, "item": "bin", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
failed: [127.0.0.1] => (item=include) => {"failed": true, "item": "include", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
failed: [127.0.0.1] => (item=lib) => {"failed": true, "item": "lib", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
failed: [127.0.0.1] => (item=share/doc) => {"failed": true, "item": "share/doc", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
failed: [127.0.0.1] => (item=share/man/man1) => {"failed": true, "item": "share/man/man1", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
failed: [127.0.0.1] => (item=share/systemtap/tapset) => {"failed": true, "item": "share/systemtap/tapset", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

**Comment by pumazi** [comment]
I believe I fixed this issue in https://github.com/Connexions/cnx-deploy/commit/6d89da839589b445fa3ce204fa6f80ad09c30b5d which was a missed condition in https://github.com/Connexions/cnx-deploy/commit/876e39c9eaf06e43c10a4c7c27d7b30239afabec.

**Comment by aw30** [comment]
Negative, replaced the build_webview.yml file and it's still getting the same error, it's still trying to sudo locally.

**Comment by pumazi** [comment]
@karenc It appears that the npm install on Debian requires sudo access to the host machine. Any way around that?

**Comment by karenc** [comment]
I think sudo is necessary for installing node.

**Comment by karenc** [comment]
May be it's not necessary...  I'll have a look.
